"""secret-guard public API."""

from .identify import (
    Assignment,
    PublicEndpoint,
    SensitiveKind,
    classify_key_name,
    classify_value,
    is_high_confidence_secret_value,
    is_common_public_ip,
    is_interesting_public_ip,
    is_public_ip,
    is_sensitive_key,
    is_unusual_public_endpoint,
    looks_like_placeholder,
    normalize_key_name,
    parse_assignment,
    parse_ip_port,
)
from .findings import Finding, ScanReport, SkippedFile
from .redaction import RedactedValue, one_line_preview, redact_result, redact_text, redact_value
from .rewrite import RewriteApplyResult, RewriteChange, RewritePlan, apply_rewrite_plan, build_rewrite_plan, can_rewrite_path
from .scan import FileKind, classify_file, fingerprint_secret, has_findings, iter_scan_files, scan_file, scan_file_report, scan_git_history, scan_high_confidence_file_chunks, scan_high_confidence_text, scan_path, scan_path_report, scan_sqlite, scan_text

__all__ = [
    "Assignment",
    "Finding",
    "FileKind",
    "PublicEndpoint",
    "RedactedValue",
    "RewriteChange",
    "RewriteApplyResult",
    "RewritePlan",
    "ScanReport",
    "SensitiveKind",
    "SkippedFile",
    "classify_key_name",
    "classify_value",
    "is_common_public_ip",
    "is_high_confidence_secret_value",
    "is_interesting_public_ip",
    "is_public_ip",
    "is_sensitive_key",
    "is_unusual_public_endpoint",
    "looks_like_placeholder",
    "normalize_key_name",
    "one_line_preview",
    "parse_assignment",
    "parse_ip_port",
    "redact_text",
    "redact_value",
    "redact_result",
    "build_rewrite_plan",
    "apply_rewrite_plan",
    "can_rewrite_path",
    "classify_file",
    "fingerprint_secret",
    "has_findings",
    "iter_scan_files",
    "scan_file",
    "scan_file_report",
    "scan_git_history",
    "scan_high_confidence_file_chunks",
    "scan_high_confidence_text",
    "scan_path",
    "scan_path_report",
    "scan_sqlite",
    "scan_text",
]
